//! settings.rs
pub const STOCK_LIST_COUNT:usize = 30;
pub static STOCK_LIST:[&'static str; STOCK_LIST_COUNT] =
    [
        "arvl",
        "aal",
        // "aapl",
        // "amzn",
        "bac",
        "bbai",
        "brds",
        // "cost",
        // "dis",
        "f",
        "ffie",
        "gns",
        // "goog",
        "htcr",
        // "msft",
        "muln",
        // "nflx",
        "nio",
        // "nvda",
        "plug",
        // "pypl",
        "sklz",
        "sono",
        // "tgt",
        // "tsla",
        "xela",

        // new
        // https://www.nasdaq.com/market-activity/most-active
        "sofi",
        "pacw",
        "amd",
        "intc",
        "wbd",
        "imgn",
        "arnc",
        "uber",
        "lyg",
        "imgn",
        "t",
        "pfe",
        "w",
        "gm",
        "sq",

    ];