services:
  frontend:
    image: rust
    ports:
      - "443:8043"
    networks:
      - front-tier
      - back-tier
#    configs:
#      - httpd-config
    secrets:
      - server-certificate

  backend:
    image: postgres
#    volumes:
#      - db-data:/etc/data
    environment:
      - POSTGRES_PASSWORD
    networks:
      - back-tier
#    environment:
#      - POSTGRES_PASSWORD=TPzC3jRH6ChKJw3MKKr6Gdkoroj7VUcuoYbomAAgBgMDYjVDJv38Jmb



#volumes:
#  db-data:

#configs:
#  httpd-config:
#    external: true

#secrets:
#  server-certificate:
#    external: true
#
networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
