# Dockerfile for backend_rest

# build stage
FROM rust:1.68.2 as builder
RUN apt-get update && apt-get -y upgrade && apt install lld clang -y
WORKDIR /app
COPY . .
#COPY common_lib .
#COPY backend_rest .
#COPY *.json .
ENV SQLX_OFFLINE=true
RUN cargo build -p backend_rest --release

# runtime stage
FROM rust:1.68.2-slim as runtime
WORKDIR /app
COPY --from=builder /app/target/release/backend_rest backend_rest
COPY backend_rest/.env .
# COPY backend/config/configuration.yaml .
ENTRYPOINT ["./backend_rest"]

