# Dockerfile for backend

# build stage
FROM rust:1.68.2 as builder
RUN apt-get update && apt-get -y upgrade && apt install lld clang -y
WORKDIR /app
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build -p backend --release

# runtime stage
FROM rust:1.68.2-slim as runtime
WORKDIR /app
COPY --from=builder /app/target/release/backend backend
COPY backend/.env /app
COPY backend/config /app
ENTRYPOINT ["./backend"]

