# Dockerfile

FROM rust:1.68.2 as builder
RUN apt-get update && apt-get -y upgrade && apt install lld clang -y
WORKDIR /app
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build -p frontend --release

# runtime stage
FROM rust:1.68.2-slim as runtime
WORKDIR /app
COPY --from=builder /app/target/release/frontend frontend
COPY frontend/.env .
# copy the contents of static (the templates folder) to a path that works without drama equally in/out of docker
COPY frontend/static /app/frontend/static

# relative to the Dockerfile
COPY frontend/config /app/frontend/config
ENTRYPOINT ["./frontend"]

