# Dockerfile

# build stage
FROM rust:1.68.2 as builder
RUN apt-get update && apt-get -y upgrade && apt install lld clang -y
WORKDIR /app
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build -p frontend --release

# runtime stage
FROM rust:1.68.2-slim as runtime
WORKDIR /app
COPY --from=builder /app/target/release/frontend frontend
COPY frontend/.env .
MKDIR /app/config/
COPY frontend/config ./config/
MKDIR /app/static/
COPY frontend/static ./static/

ENTRYPOINT ["./frontend"]

